<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-02T13:52:41</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d314b5a1-e602-4dec-aac6-dc591ee3f13c</testSuiteGuid>
   <testCaseLink>
      <guid>923c32bc-446f-4412-bca1-6ad452bcf716</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenTestingSSRec</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>932b4087-cd5b-4b7b-8844-548e6ca02e88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66583c2e-b58a-445f-9da1-982281ce3933</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7b21fae-a02a-47a7-9973-2e46d989d2eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f260fbb0-c3a1-49fe-8210-9c9ba7ebb640</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ElementHighLight</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbda8519-d91f-4095-9be1-6710ac25c958</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56c3d12e-e769-4730-94ec-cb4b1b211af0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c94a6d9f-be64-4b78-b9c0-cf5497a44b55</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
